config/routes.rb
Rails.application.routes.draw do
  root 'picture_stories#home'
  resources :picture_stories
end

app/models/picture_story.rb
class PictureStory < ActiveRecord::Base
  has_many :picture_story_orders
  accepts_nested_attributes_for :picture_story_orders, allow_destroy: true
end

app/models/picture_story_order.rb
class PictureStoryOrder < ActiveRecord::Base
  belongs_to :picture_story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/picture_stories_controller.rb
class PictureStoriesController < ApplicationController

  def home
  end

  def new
    @picture_story = PictureStory.new
    3.times { @picture_story.picture_story_orders.build }
  end

  def create
    orders_attributes = params[:picture_story][:picture_story_orders_attributes]
    orders_attributes.each do |key, value|
      text = value[:story]
      words = get_words(text)
      words ||= {'surface' => '面白'}
      search_words = find_search_words(words)
      count = search_words.length
      if count >= 3
        @output = get_choice(search_words, 3)
      elsif count >= 2
        @output = get_choice(search_words, 2)
      else
        @output = get_choice(search_words, 1)
      end
      url = search_image(@output)
      if !url
        @output = get_choice(search_words, 1)
        url = search_image(@output)
      end
      file_name = save_image_and_get_file_name(url)
      orders_attributes[key][:image] = file_name
    end
    @picture_story = PictureStory.create(picture_story_params)
    redirect_to @picture_story
  end

  def show
    @picture_story = PictureStory.find(params[:id])
    orders = @picture_story.picture_story_orders
    orders.each do |order|
      save_image_and_get_file_name(order[:image])
    end
  end

  def index
    @picture_stories = PictureStory.all
  end

  private

    def picture_story_params
      params.require(:picture_story).permit(:title, picture_story_orders_attributes: [:id, :story, :image, :_destroy])
    end

    def get_words(text)
      encoding_text = CGI.escape(text)
      url = 'http://jlp.yahooapis.jp/MAService/V1/parse?appid=dj0zaiZpPVBhTTlleGkwc0J1MSZzPWNvbnN1bWVyc2VjcmV0Jng9Yzg-&sentence=' + encoding_text + '&results=ma&ma_filter=1%7C2%7C9%7C10'
      uri = URI.parse(url)
      req = Net::HTTP::Get.new(uri.request_uri)

      res = Net::HTTP.start(uri.host, uri.port) do |http|
        http.request(req)
      end

      body = res.body.force_encoding("utf-8")

      hash = Hash.from_xml(body)
      if hash["ResultSet"]["ma_result"]["word_list"].nil?
        return false
      end
      result = hash["ResultSet"]["ma_result"]["word_list"]["word"]
      return result
    end

    def find_search_words(result)
      words = []
      if result.is_a?(Array)
        result.each do |word|
          next if word['pos'] != '名詞' && word['surface'].length == 1
          words.push(word['surface'])
        end
      else
        words.push(result['surface'])
      end
      return words
    end

    def get_choice(words, num)
      choices = words.sample(num)
      output = ""
      choices.each do |word|
        output += word
        output += " "
      end
      return output
    end

    def search_image(text)
      encoding_text = CGI.escape(text)

      url = "https://public-api.secure.pixiv.net/v1/search/works?q=#{encoding_text}&sort=date&per_page=20&page=1&image_sizes=small,medium&mode=text"
      token = 'Bearer yGJg-FiKrfEYnnITYD0ZPeEOLKTjQr0d9FupYux9gLU'

      uri = URI.parse(url)
      https = Net::HTTP.new(uri.host, uri.port)

      https.use_ssl = true # HTTPSでよろしく
      req = Net::HTTP::Get.new(uri.request_uri)

      req["Authorization"] = token # httpリクエストヘッダの追加
      res = https.request(req)

      # 返却の中身を見てみる
      json = JSON.parse(res.body)
      puts json
      count = json['count']
      return false if count == 0
      image = json['response'].sample
      image_urls = image['image_urls']
      return image_urls['medium']
    end

    def save_image_and_get_file_name(url)
      uri = URI.parse(url)
      req = Net::HTTP::Get.new(uri.request_uri)
      req["Referer"] = 'https://public-api.secure.pixiv.net' # httpリクエストヘッダの追加

      @res = Net::HTTP.start(uri.host, uri.port) do |http|
        http.request(req)
      end

      file_name = url.gsub(/[\s\/]/, '')
      File.open("public/images/#{file_name}", "wb") {|f| f.write(@res.body)}
      return url
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_stories_helper.rb
module PictureStoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PixivStory</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', rel='stylesheet' %>
  <%= stylesheet_link_tag 'https://code.getmdl.io/1.2.1/material.indigo-pink.min.css', rel='stylesheet' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://code.getmdl.io/1.2.1/material.min.js', defer='defer' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">PixivStory</span>
        <div class="mdl-layout-spacer"></div>
        <button id="demo-menu-lower-right"
          class="mdl-button mdl-js-button mdl-button--icon">
          <i class="material-icons">more_vert</i>
        </button>
      <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
        for="demo-menu-lower-right">
        <%= link_to "ホーム", root_path, class: "mdl-menu__item", "data-no-turbolink" => true %>
        <%= link_to "ストーリー作成", new_picture_story_path, class: "mdl-menu__item", "data-no-turbolink" => true %>
        <%= link_to "ストーリー一覧", picture_stories_path, class: "mdl-menu__item", "data-no-turbolink" => true %>
      </ul>
    </div>
  </header>
  <main class="mdl-layout__content">
    <div class="page-content">
      <%= yield %>
    </div>
  </main>
</div>

</body>
</html>

app/views/picture_stories/_picture_story_order_fields.html.erb
<div class="nested-fields">
  <div class="story-wrapper">
    <%= f.text_area :story, class: 'story-fields', placeholder: 'ストーリー' %>
    <%= link_to_remove_association '削除', f, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent remove-story-fields-btn' %>
  </div>
</div>

app/views/picture_stories/home.html.erb
<div class="container2">
  <h3 class="home-title">Pixiv Story</h3>
  <p class="home-description">Pixiv Storyは暇を持て余した人たちが使う絵本作成サイトです</p>
  <div class="demo-card-wide mdl-card mdl-shadow--2dp home-card-wide">
    <div class="mdl-card__title more-story">
      <h2 class="mdl-card__title-text">物語の文章を考える</h2>
    </div>
  </div>
  <div class="demo-card-wide mdl-card mdl-shadow--2dp home-card-wide">
    <div class="mdl-card__title more-story">
      <h2 class="mdl-card__title-text">投稿する</h2>
    </div>
  </div>
  <div class="demo-card-wide mdl-card mdl-shadow--2dp home-card-wide">
    <div class="mdl-card__title more-story">
      <h2 class="mdl-card__title-text">イラストが自動でマッチング</h2>
    </div>
  </div>
  <p class="home-description">この3ステップで簡単に自分の絵本を作ることができます。</p>
  <p class="home-description">早速、自分のストーリーを作ってみましょう！</p>
  <%= link_to "ストーリー作成へ", new_picture_story_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect home-btn" %>
  <div class="home-last"></div>
</div>

app/views/picture_stories/index.html.erb
<div class="content-wrapper">
  <p class="index-story-title">ストーリー一覧</p>
  <div class="list-action mdl-list">
  <% @picture_stories.each do |pic_story| %>
    <div class="mdl-list__item">
      <span class="mdl-list__item-primary-content">
        <i class="material-icons mdl-list__item-avatar">star</i>
        <%= link_to pic_story[:title], pic_story %>
      </span>
    </div>
  <% end %>
  </div>
</div>

app/views/picture_stories/new.html.erb
<%= form_for(@picture_story) do |f| %>
  <div class="content-wrapper">
    <p class="new-story-title">ストーリーを作ろう</p>
    <%= f.text_field :title, class: 'title-fields', placeholder: 'タイトル' %>
    <%= f.fields_for :picture_story_orders do |order, index| %>
      <%= render 'picture_stories/picture_story_order_fields', f: order %>
    <% end %>
    <div class="fields">
      <%= link_to_add_association 'ストーリーを追加する', f, :picture_story_orders, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent add-association' %>
    </div>
    <%= f.submit '投稿', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored submit-btn' %>
  </div>
<% end %>

app/views/picture_stories/show.html.erb
<div class="container">
  <h3><%= @picture_story.title %></h3>
  <div class="main-carousel">
    <% @picture_story.picture_story_orders.each do |order| %>
      <div class="carousel-cell">
        <p><%= order.story %></p>
        <% if order.image? %>
          <% path = order.image.gsub(/[\s\/]/, '') %>
          <%= image_tag path %>
        <% end %>
      </div>
    <% end %>
    <div class="carousel-cell">
      <p class="finish-title">これでストーリーはおしまいです。</p>
      <div class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title more-story">
          <h2 class="mdl-card__title-text">Pixiv Story</h2>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to "他のストーリーも見てみる", picture_stories_path, class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
        </div>
      </div>
      <div class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title create-story">
          <h2 class="mdl-card__title-text">Pixiv Story</h2>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to "自分でストーリーを作ってみる", new_picture_story_path, class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_tag do %>
$(document).ready(function () {
  var height = screen.availHeight
  $('.container').css("height", height * 0.95 + "px")
  $('.carousel-cell').css("height", (height - 50) + "px")
  $('.main-carousel').flickity({
    cellAlign: 'left',
  });
});
<% end %>